feat_keys:
  nn:
    #- gru_1539004952
    #- gru_1539056285

    #- B_gru_1539352680
    #- A_gru_1539352687

    #- B_gru_1539353092
    #- A_gru_1539353088
    #- semeval2014_task9.gru_1539175546
    #- semeval2018_task1.love_gru_1539178720

    #- A_gru_naive_1540912745
    #- B_gru_naive_1540913413
    #- A_gru_ek_1540912707
    #- B_gru_ek_1540913409

    #- A_lstm_ek_1541078091
    #- A_lstm_ek_1541078223

    #- A_gru_ek_1541081331
    #- A_gru_naive_1541081642

    #- B_gru_ek_1541081942
    #- B_gru_naive_1541081919

    #- A_gru_ek_1542446279
    #- A_gru_ek_1542446159
    #- B_gru_ek_1542448031

  offline:
    #- inc_emb.google_ek
    #- inc_emb.glove_25_ek
    #- inc_emb.glove_50_ek
    #- inc_emb.glove_100_ek
    #- inc_emb.glove_200_ek

    #- inc_emb_w.google_ek_dot

    #- inc_emb_w.google_ek
    #- inc_emb_w.glove_25_ek
    #- inc_emb_w.glove_50_ek
    #- inc_emb_w.glove_100_ek
    #- inc_emb_w.glove_200_ek

    #- weka
    #- weka_ek

    #- tf_ek
    #- tf_naive

    #- inc_emb.ntua_ek
    #- inc_emb_w.ntua_ek

    #- nbow_google_ek_max
    #- nbow_google_ek_min
    #- nbow_google_ek_mean
    #- nbow_google_ek_sum

    #- nbow_ntua_ek_mean


train:
  use_class_weights: True
