module: algo.nn.ntua
version:
  w2v: ntua

nn:
  seq_len: _
  embedding:
    trainable: False
  rnn:
    dim: 50
  attention:
    dim: 50
  learning_rate:
    init: 0.01
    decay_steps: 1
    decay_rate: 0.9
  l2_reg_lambda: 0.1
  output:
    dim: _
  binary_classification: False

train:
  epoch: 30
  valid_rate: 0.
  batch_size: 100
  dropout_keep_prob: 0.2
  use_class_weights: True
