module: algo.nn.gru
dataset_key: semeval2018_task3
label_version: A

nn:
  seq_len: _
  embedding:
    trainable: True
  rnn:
    dim: 100
  learning_rate:
    init: 0.01
    decay_steps: 1
    decay_rate: 0.9
  l2_reg_lambda: 0.1
  output:
    dim: _

train:
  epoch: 1
  valid_rate: 0.2
  batch_size: 100
  dropout_keep_prob: 0.5
  use_class_weights: True
