module: algo.nn.ntua
analyzer: char
word:
  w2v_version: ntua
  randomize_not_supported: True
  min_tf: 2.
char:
  embedding_dim: 25

nn:
  seq_len: _
  embedding:
    trainable: True
    noise_stddev: 0.
  rnn:
    dim: 50
  attention:
    dim: 50
  learning_rate:
    init: 0.01
    decay_steps: 1
    decay_rate: 0.9
  l2_reg_lambda: 0.1
  output:
    dim: _
  binary_classification: False

train:
  epoch: 80
  valid_rate: 0.
  batch_size: 32
  dropout_keep_prob: 0.2
  use_class_weights: True
